### ISSUE TITLE
Update embedded eureka extension calls to use new helper methods after 0.12.0 of embedded-eureka is released

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/service-discovery-client#105]

**Comment by sleberknight** [comment]
There is also some code that no longer compiles due to some renaming, e.g. from `registeredApplications()` to `getRegisteredApplications()`

**Comment by sleberknight** [comment]
And also need to change from `re-retrying` library to `retrying-again` since kiwi 0.21.0 switched.
