### ISSUE TITLE
Why is registryUrls protected in EurekaConfig instead of private?

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/service-discovery-client#160]
I can't see any reason why `registryUrls` in `EurekaConfig` is `protected`. Our only subclass (`EurekaRegistrationConfig`) doesn't reference it in any way.

Also, I don't think we should change the major version for making this `private`. Maybe technically SemVer requires that, but I can make a sideways sort of argument that `protected` is not really part of the _public_ API.

**Comment by chrisrohr** [comment]
Not a major bump
