### ISSUE TITLE
Update to build on both JDK 11 and 17

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/service-discovery-client#236]

**Comment by sleberknight** [comment]
The embedded-consul JUnit extension might cause problems for us. It is implemented in Groovy, and when running tests that use it, there are illegal reflective access warnings. Example output:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/local/user/share/mvn_repo/org/codehaus/groovy/groovy/2.5.14/groovy-2.5.14.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I am about 99.99% sure this will fail in JDK 17.

The last release of embedded-consul was in April 2021, and it is using Groovy 2.5.14. As of this writing, the latest version of Groovy is 3.0.12. I have no idea whether the library would "just work" with an updated version of Groovy, or whether Groovy 3.x still has the illegal reflection access problem.

Maybe we should consider switching the Consul tests to use test containers like we did for Eureka...

**Comment by sleberknight** [comment]
The official documentation on [Hashicorp Consul Module](https://www.testcontainers.org/modules/consul/) seems wrong, since the dependency they mention doesn't exist in Maven Central (group ID `org.testcontainers` and artifact ID `consul`). The fact that it was using an old JUnit 4 `@ClassRule` was also a hint there was something amiss.

I googled and found this alternative: https://github.com/hmhco/testcontainers-consul from a [blog post](https://hmh.engineering/testcontainers-for-hashicorp-consul-and-vault-85f2bba14290)

**Comment by sleberknight** [comment]
Alas, the alternative I found doesn't seem to be very active, so maybe not a good idea to just start using it. I did, however, run the tests locally on JDK 17 and they all passed, both running maven on the command line as well as in IntelliJ after switching the project to JDK 17 for both SDK and Language Level. So, maybe that "illegal reflective access" error was some kind of red herring.

**Comment by chrisrohr** [comment]
Now that we are using TestContainers instead of the embedded eureka, we can support Java 17
